apiVersion: v1
kind: Service
metadata:
  name: ledger-api-canary
  namespace: payments
  labels:
    app: ledger-api
    rollout: canary
spec:
  selector:
    app: ledger-api
    rollout: canary
  ports:
    - name: http
      port: 8080
      targetPort: 8080
